;;emacs配置程序.

(add-to-list 'load-path (expand-file-name "~/.emacs.d"))
(add-to-list 'load-path "/Users/zhuoyikang/.emacs.d/site-lisp")

(require 'init-ido)
(require 'init-key-press)
(require 'init-winner)
(require 'init-misc)
(require 'init-session)
(require 'init-complete)
(require 'init-erlang)
(require 'init-ruby)
(require 'init-lua)
(require 'init-template)
(require 'init-shell)
(require 'init-yasnippet)
(require 'init-git)
(require 'init-linum)
(require 'init-white-space)
(require 'init-slime)
(require 'init-mark-down)
(require 'init-xterm)

(message "yikang zhuo's emacs launch")
