;;emacs配置程序.
(add-to-list 'load-path (expand-file-name "~/.emacs.d"))
(add-to-list 'load-path "/Users/zhuoyikang/.emacs.d/site-lisp")
(message "enjoy!!!")

(require 'init-linum)
(require 'init-org)
(require 'init-locales)
(require 'init-utils)
(require 'init-ido)
(require 'init-key-press)
(require 'init-winner)
(require 'init-misc)
(require 'init-go)
(require 'init-complete)
(require 'init-ruby)
(require 'init-lua)
(require 'init-template)
(require 'init-shell)
(require 'init-yasnippet)
(require 'init-git)

;;(require 'init-white-space)
(require 'init-slime)
(require 'init-elisp)
(require 'init-mark-down)
(require 'init-xterm)
(require 'init-csv)
(require 'init-ibuffer)
;;should work with windows system
(require 'init-highlight-tail)
(require 'init-server)
(require 'init-erlang)
(require 'init-custom)
(require 'init-session)

